### PR TITLE
Add zone append command

### PR DESCRIPTION
**Pull request by yfwayne**
Add zone append command in zns.py

### CODE REVIEW

**Comment by yfwayne** [comment]
Can you see the submodule in conformance synced with the approved PR ? Plus the commit ec0e652 - Use newly defined zone append command in test_zns.py?

**Comment by cranechu** [comment]
> Can you see the submodule in conformance synced with the approved PR ? Plus the commit ec0e652 - Use newly defined zone append command in test_zns.py?

No, cannot see updated test_zns.py with newly defined zone append command. 

Furthermore, I think we can remove nsid and slba from append's parameter list. They are available in zone objects.

**Comment by yfwayne** [comment]
the slba was there because we need to test the zone append command property regarding start lba. If we strictly use the Zone object, then we lose the capability to test that. But I agree that we can remove nsid since a zone would always inside one namespace, there is not test needed. but better keep slba for more flexible test of zone append start requirements.

**Comment by yfwayne** [comment]
Cancel this pr to wait for PR in the conformance package pr # 42 to check-in first: Use zone append command #42

**Pull request closed without merging**
